### ISSUE TITLE
hello @AseemWangoo  it is a really nice one to build flutter web, but how can i load dynamic url in iframe. in  alert diaolg?

### ISSUE THREAD

**Issue by SSVernekar** [AseemWangoo/experiments_with_web#1]
I tried this one.

// ignore: avoid_web_libraries_in_flutter
import 'dart:html';
import 'dart:ui'  as ui;

import 'package:flutter/material.dart';

// ignore: must_be_immutable
class IframeView extends StatefulWidget {

  String url;
  IframeView(this.url);
  @override
  _IframeViewState createState() => _IframeViewState();
}

class _IframeViewState extends State<IframeView> {
  final IFrameElement _iframeElement = IFrameElement();

    Widget _iframeWidget;

 

  @override
  void initState() {
 _iframeElement.height = '500';
_iframeElement.width = '500';
_iframeElement.src = widget.url;
 _iframeElement.style.border = 'none';
// ignore: undefined_prefixed_name

ui.platformViewRegistry.registerViewFactory('iframeElement',
 (int viewId) {
   
   
   print('a');
   
   return _iframeElement;
 });

  _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    // setState(() {
    //   _iframeElement.src=widget.url;
    // });
    return Container( margin: EdgeInsets.only(top:50),child: _iframeWidget,
      
    );
  }
}

but it loads first loaded url again and again.

**Comment by SSVernekar** [comment]
@AseemWangoo  Please help me

**Comment by AseemWangoo** [comment]
Is the source code (published in the article) also giving this error ?

**Comment by SSVernekar** [comment]
thank u i got solution
