### ISSUE TITLE
iFrame is reloaded when hover on back or menu button

### ISSUE THREAD

**Issue by alihusseinalissa** [AseemWangoo/experiments_with_web#2]
When I hover the mouse on back button or on menu button, the iFrame element is rebuilt or reloaded, the console is not show anything about the issue.

**Comment by AseemWangoo** [comment]
Will take a look. I think we need to follow this 

https://github.com/flutter/flutter/issues/53253#issuecomment-607197549

**Comment by AseemWangoo** [comment]
May you try the new iframe widget here?

https://github.com/AseemWangoo/experiments_with_web/blob/master/lib/app_level/widgets/desktop/custom_iframe.dart.

**Comment by AngusPei** [comment]
> May you try the new iframe widget here?
> 
> https://github.com/AseemWangoo/experiments_with_web/blob/master/lib/app_level/widgets/desktop/custom_iframe.dart.

@AseemWangoo 
Do you have this problem? [#54027](https://github.com/flutter/flutter/issues/54027)

**Comment by alihusseinalissa** [comment]
> May you try the new iframe widget here?
> 
> https://github.com/AseemWangoo/experiments_with_web/blob/master/lib/app_level/widgets/desktop/custom_iframe.dart.

Yes this is working, thank you. Closing the issue.

**Comment by AseemWangoo** [comment]
> > May you try the new iframe widget here?
> > https://github.com/AseemWangoo/experiments_with_web/blob/master/lib/app_level/widgets/desktop/custom_iframe.dart.
> 
> @AseemWangoo
> Do you have this problem? [#54027](https://github.com/flutter/flutter/issues/54027)

Unfortunately, yes :(
