### ISSUE TITLE
cant start because error PersistentHeaderShowOnScreenConfiguration not defined

### ISSUE THREAD

**Issue by fardump** [AseemWangoo/experiments_with_web#3]
### cant start because error PersistentHeaderShowOnScreenConfiguration not defined
hello sir, i wanted to ask.. so i've try your repo which one is experiment with web. when i try to run it, it shown error and the error said

**lib/app_level/widgets/dekstop/sliver_scaffold.dart**

line 245 Error: Type 'PersistentHeaderShowOnScreenConfiguration' not found.
line 246 Error: The method 'PersistentHeaderShowOnScreenConfiguration' isn't defined for the class '_SliverDelegate'.

what should i do? tbh im new on flutter world. thanks

**Comment by AseemWangoo** [comment]
Have you pulled the latest branch?

**Comment by AseemWangoo** [comment]
More importantly, you need to be on flutter beta channel.

flutter channel beta
flutter upgrade
