### ISSUE TITLE
 Mozilla GeoLocation not work

### ISSUE THREAD

**Issue by tazik561** [AseemWangoo/experiments_with_web#4]
I try to use `navigator.geolocation` like this on my flutter web :
```
@JS('navigator.geolocation') // navigator.geolocation namespace
library jslocation; // library name can be whatever you want

import "package:js/js.dart";

@JS('getCurrentPosition') // Accessing method getCurrentPosition from       Geolocation API
external void getCurrentPosition(Function success(GeolocationPosition pos));

@JS()
@anonymous
class GeolocationCoordinates {
  external double get latitude;
  external double get longitude;
  external double get altitude;
  external double get accuracy;
  external double get altitudeAccuracy;
  external double get heading;
  external double get speed;

  external factory GeolocationCoordinates(
      {double latitude,
      double longitude,
      double altitude,
      double accuracy,
      double altitudeAccuracy,
      double heading,
      double speed});
}

@JS()
@anonymous
class GeolocationPosition {
  external GeolocationCoordinates get coords;

  external factory GeolocationPosition({GeolocationCoordinates coords});
}
```
And i use it :

```
  @override
  void initState() {
    super.initState();
    _getLocation();
  }

```
```
  Future _getLocation() async {
    if (kIsWeb) {
      print("-----> web js");
      getCurrentPosition(allowInterop((pos) => success(pos)));
    } }
```
```
  success(pos) {
    try {
      print(pos.coords.latitude);
      print(pos.coords.longitude);
      setState(() {
        _loading = false;
        print(
            '${widget.url}?BranchName=&latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}');
      });
    } catch (ex) {
      print("Exception thrown : " + ex.toString());
    }
  }
```
But success method never called?I check https://fir-signin-4477d.firebaseapp.com/#/location page and Mozilla GeoLocation is not work like me.
What is the problem?  

This is my question on stackoverflow : https://stackoverflow.com/questions/64411270/flutter-web-get-location-on-web-by-location-plugin

**Comment by AseemWangoo** [comment]
Questions

1. Which browser are you using, Chrome?
2. Is my website able to give you location on your browser?

**Comment by tazik561** [comment]
1 - Chrome, flutter runs by default on Chrome. 
2. In Chrome, your website did not give my location.

**Comment by AseemWangoo** [comment]
Interesting,

Can you try opening the website on **Chrome Incognito?**

1. Inside my website Go to **location option** -> Click on **Mozilla Geolocation**

It should give you a prompt (asking your permission to access the location).
Click Allow and wait for 2-3 seconds, until the coordinates are shown on the screen

Let me know what's the result

**Comment by tazik561** [comment]
I do but nothing happen !!
https://pasteboard.co/JwlH43Y.png
I was waited for 15 min but lat and long ware 0

**Comment by AseemWangoo** [comment]
Hmm, as from the image, I suppose you have linux and using chrome.

Theoretically, I don't think that should be a problem though.
SInce, I am using mac + chrome, the popup is shown to me 

and on clicking allow, it gives me coords

**Comment by tazik561** [comment]
Yes, I am Linux user,You now, I use Mozilla geolocation on my flutter web and i can get location ....

**Comment by AseemWangoo** [comment]
For the restrictions thing, maybe we can check like this.

Kindly open the website on your phone inside the Chrome browser.

**Please note the website will look ugly on mobile.**

Try to open the location option and follow the steps as usual?

**Comment by tazik561** [comment]
I tried In mobile, but in mobile like above, Mozilla Geolocation did not work too.

**Comment by AseemWangoo** [comment]
That's really sad :(

One final attempt, can you try calling this api (https://geolocation-db.com/json/)?

**Simply copy-paste in your web browser**

**Comment by tazik561** [comment]
It's return a location  but it's location is very far from my location .

**Comment by AseemWangoo** [comment]
Oh, no.

I am out of ideas mate! :(

**Comment by AseemWangoo** [comment]
I will monitor this issue but in case you are having any doubts, please feel free to open this :)
