### ISSUE TITLE
check box in paginating data table ?

### ISSUE THREAD

**Issue by johnyenatu** [AseemWangoo/experiments_with_web#5]
am trying to add and control checkbox's  in your example but it's not working can you help please?

**Comment by AseemWangoo** [comment]
Are you adding a checkbox for selecting a row?
May you share the snippet?

Also, if I recall correctly, paginated data table has a property for selecting a row (which if set true) automatically inserts a checkbox. (you can play with this)

**Comment by johnyenatu** [comment]
check box are visible but the are not responsible for on select events I used your source code but the data table am going to design have complex functionality.

**Comment by AseemWangoo** [comment]
In case that's your custom code, I don't think I can be useful

**Comment by johnyenatu** [comment]
yeah you are right ,but now am able to work with check boxes ,before we close can you share ideas with me how can I implement search capability for paginating data table .

**Comment by AseemWangoo** [comment]
For implementing search, I recently wrote an article, maybe that could help?

https://flatteredwithflutter.com/how-to-implement-search-in-flutter-web/

**Comment by AseemWangoo** [comment]
In case you are still facing issues, please feel free to reopen this :)
