### ISSUE TITLE
Wasm with Flutter

### ISSUE THREAD

**Issue by devopsi** [AseemWangoo/experiments_with_web#6]
hello AseemWangoo,
I followed your tutorial (article, video) to use Wasm in Dart/Flutter with wasm_interop package(thank you for that). Can you please help me with this issue : 
https://stackoverflow.com/questions/68316438/how-to-get-variables-value-from-custom-js-and-use-it-in-flutter-web-dart
I really don't now how to solve it.

**Comment by AseemWangoo** [comment]
Any help from this link?
https://github.com/EPNW/web_ffi/tree/master/example
