### ISSUE TITLE
Shall we call method from js file in dart file?

### ISSUE THREAD

**Issue by pradeep-kumar-rs** [AseemWangoo/experiments_with_web#8]
for example

in example.js
`function alertMessage(text) {
    alert(text)
}

window.logger = (flutter_value) => {
   console.log({ js_context: this, flutter_value });
}`

main.dart
void main() {
  js.context.callMethod('alertMessage', ['Flutter is calling upon JavaScript!']);
// var state = js.JsObject.fromBrowserObject(js.context['state']);
// print(state['hello']);
  
}

**Comment by AseemWangoo** [comment]
seems correct. Refer to the sample code in the repo also
