### ISSUE TITLE
Url json

### ISSUE THREAD

**Issue by CadisRaziel** [AseemWangoo/experiments_with_web#9]
Hello friend, I saw your article on how to get a user's location...
a question, where does this json "https://geolocation-db.com/json/" come from?
is it your database?

Can I use it for something professional?

**Comment by AseemWangoo** [comment]
Hello,

This is a website, which I used for a demo. No, it's not from my database.
Personally, I would not recommend it for a professional use case, maybe try
a paid one?

Stay healthy,


Aseem Wangoo

Software Engineer

flatteredwithflutter.com

+65 96156442

<https://youtube.com/aseemwangoo> <https://twitter.com/aseemwangoo>
***@***.***> <https://flatteredwithflutter.com/>

**Comment by CadisRaziel** [comment]
thank u bro =)
